#!/usr/bin/env perl
use strict;
use warnings;
use 5.010;

my $man_path = "$ENV{HOME}/var/code/feh/man/feh.pre";
my $comp_path = "$ENV{HOME}/packages/zsh/etc/completions/_feh";

my @options;

open(my $comp_file, '<', $comp_path) or die("Can't open $comp_path: $!");
while (my $line = <$comp_file>) {

	if ($line =~ /^ \t '(?<long> [\w-]+ )' \s+ '(?<short> . ) \+? ' $/xo) {
		push(@options, [@+{'short', 'long'}]);
	}
	elsif ($line =~ /^ \t ' \*? -- (?<long> [\w-]+ ) \[/xo) {
		push(@options, [undef, $+{'long'}]);
	}

}
close($comp_file);

open(my $man_file, '<', $man_path) or die("Can't open $man_path: $!");
while (my $line = <$man_file>) {

	if ($line !~ /^ \.It \s Cm \s (?: -(?<short> . ) \s , )? --(?<long> [\w-]+ )/xo) {
		next;
	}

	if ($+{'long'} =~ / ^ action \d $ /xo) {
		next;
	}

	if (not grep { $_ ~~ [@+{'short', 'long'}] } @options) {
		printf("not in completion: %s %s\n",
			$+{short} || ' ', $+{long},
		);
	}

}
close($man_file);
