#!/usr/bin/env zsh
typeset -a audio video image
eval $(perl -ne 'if (/^mime_\w+\=\(/ or $found == 1) { $found = 1; print } if (/^\)/ and $found == 1) {$found = 0}' ~/.zshrc)

while read mime extensions; do
	[[ $mime == audio/* ]] && audio+=(${(s/ /)extensions})
	[[ $mime == video/* ]] && video+=(${(s/ /)extensions})
	[[ $mime == image/* ]] && image+=(${(s/ /)extensions})
done < /etc/mime.types

audio=(${(i)audio})
video=(${(i)video})
image=(${(i)image})

for mimetype in $audio; {
	[[ ${mime_audio[(I)$mimetype]} == 0 ]] && echo "mime_audio+=$mimetype"
}
for mimetype in $video; {
	[[ ${mime_video[(I)$mimetype]} == 0 ]] && echo "mime_video+=$mimetype"
}
for mimetype in $image; {
	[[ ${mime_image[(I)$mimetype]} == 0 ]] && echo "mime_image+=$mimetype"
}

echo "mime_audio=($audio)"
echo "mime_video=($video)"
echo "mime_image=($image)"
